import type { Metadata } from 'next'
import { ArrowRight } from 'lucide-react'

export const metadata:Metadata={title:'Event Types | RunYourEvent',description:'RunYourEvent leads with company events, then wedding and reunion execution, with nonprofit, volunteer, sports, charity, church, community and school expansion only where event-specific depth is justified.',alternates:{canonical:'/event-types'}}

const primary=[
  ['Company & corporate events','Primary commercial funnel','Build the complete execution plan across venue, program, production, guests, vendors, approvals and event day.','/company-event-planning'],
  ['Wedding planning','Consumer SEO lead','Turn the fixed wedding date into an accountable checklist, timeline and wedding-day Run of Show.','/wedding-planning-checklist'],
  ['Family reunions','Hidden organic opportunity','Coordinate travel, stays, meals, activities and family responsibilities from one operating plan.','/family-reunion-planning'],
  ['Class reunions','Underserved volunteer-led use case','Give outreach, venue, attendance, vendors, program and volunteer work clear owners and dates.','/class-reunion-planning'],
]

const expansion=[
  ['Nonprofit & volunteer-led events','Next expansion: fundraising, volunteer coordination and delivery logic—not generic volunteer-management software.'],
  ['Sports, charity, church & community events','Build only where the page can carry a genuine event-specific operating blueprint.'],
  ['PTA & school blueprints','Primarily an outreach and partnership channel rather than the main SEO wedge.'],
]

export default function Page(){return <main className="bg-[#fbfaf7]"><section className="shell py-20"><p className="eyebrow">Event Types</p><h1 className="display mt-4 max-w-5xl text-5xl font-black sm:text-6xl">Focused funnels. One event execution engine.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-[#687386]">Company events lead commercially. Weddings lead consumer search. Family and class reunions get dedicated organic funnels. We do not publish dozens of thin event pages just to capture keywords.</p><div className="mt-12 grid gap-5 md:grid-cols-2">{primary.map(([t,k,b,h])=><a key={t} href={h} className="rounded-[28px] border border-black/[.055] bg-white p-7 transition hover:-translate-y-0.5 hover:border-[#c9aa57]"><p className="text-[10px] font-black uppercase tracking-[.13em] text-[#9a7b31]">{k}</p><h2 className="mt-3 text-2xl font-black text-[#23324a]">{t}</h2><p className="mt-3 text-base leading-7 text-[#687386]">{b}</p><span className="mt-6 inline-flex items-center text-sm font-black text-[#9a7b31]">Explore <ArrowRight className="ml-2" size={14}/></span></a>)}</div><div className="mt-14"><p className="eyebrow">Expansion architecture</p><h2 className="display mt-4 max-w-3xl text-3xl font-black">Add pages only when the product can support real event-specific depth.</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{expansion.map(([t,b])=><article key={t} className="rounded-[24px] border border-black/[.055] bg-[#f5f2ea] p-6"><h3 className="font-black text-[#23324a]">{t}</h3><p className="mt-2 text-sm leading-6 text-[#687386]">{b}</p></article>)}</div></div><div className="mt-12 rounded-[28px] bg-[#15233f] p-7 text-white"><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#efcd6d]">Professional operators</p><div className="mt-3 grid gap-5 md:grid-cols-2"><a href="/agencies" className="rounded-2xl border border-white/10 p-5"><h2 className="font-black">Event teams & agencies</h2><p className="mt-2 text-sm text-white/60">Standardize execution without forcing every event into the same template.</p></a><a href="/venues" className="rounded-2xl border border-white/10 p-5"><h2 className="font-black">Hotels & venues</h2><p className="mt-2 text-sm text-white/60">Coordinate clients, suppliers and internal teams from one operating plan.</p></a></div></div></section></main>}
