import { redirect } from 'next/navigation'
import { getAdminSession } from '@/lib/admin-auth'
import { getServerSupabase } from '@/lib/supabase-server'

export const dynamic='force-dynamic'

function money(cents:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format((cents||0)/100)}
function label(segment:string){return ({company:'Company events',weddings:'Weddings',family_reunions:'Family reunions',secondary:'Secondary organic',other:'Other'} as Record<string,string>)[segment]||segment}

export default async function AdminPage(){
  const session=await getAdminSession(); if(!session) redirect('/admin/login')
  const db=getServerSupabase()
  const since7=new Date(Date.now()-7*86400000).toISOString()
  const since30=new Date(Date.now()-30*86400000).toISOString()
  const [drafts7,orders7,paid30,recentOrders,recentDrafts,activity]=await Promise.all([
    db.from('dengine_plan_drafts').select('id',{count:'exact',head:true}).gte('created_at',since7),
    db.from('dengine_orders').select('id',{count:'exact',head:true}).gte('created_at',since7),
    db.from('dengine_orders').select('amount_cents,tier,event_segment,status,created_at').eq('status','paid').gte('created_at',since30),
    db.from('dengine_orders').select('id,draft_token,tier,amount_cents,currency,status,customer_email,event_segment,created_at,verified_at,stripe_checkout_session_id,stripe_payment_intent_id').order('created_at',{ascending:false}).limit(25),
    db.from('dengine_plan_drafts').select('draft_token,event_summary,recommended_tier,event_segment,created_at,expires_at').order('created_at',{ascending:false}).limit(25),
    db.from('dengine_conversion_events').select('id,event_name,draft_token,event_segment,metadata,created_at').order('created_at',{ascending:false}).limit(40),
  ])
  const paid=paid30.data||[]; const revenue=paid.reduce((s,r)=>s+(r.amount_cents||0),0)
  const segmentStats=['company','weddings','family_reunions','secondary','other'].map(seg=>({seg,previews:(recentDrafts.data||[]).filter(r=>r.event_segment===seg).length,orders:(recentOrders.data||[]).filter(r=>r.event_segment===seg).length,paid:paid.filter(r=>r.event_segment===seg).length,revenue:paid.filter(r=>r.event_segment===seg).reduce((s,r)=>s+(r.amount_cents||0),0)}))
  const paidCount=paid.length
  return <main className="min-h-screen bg-[#f5f2ea]"><section className="shell py-10 sm:py-14"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">RunYourEvent operations</p><h1 className="display mt-3 text-4xl font-black sm:text-5xl">Admin dashboard</h1><p className="mt-3 text-sm text-[#687386]">Monitor demand, conversion, purchases and the three primary event funnels.</p></div><form action="/api/admin/logout" method="post"><button className="btn-secondary" type="submit">Sign out</button></form></div>
  <div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Previews · 7d',drafts7.count||0],['Checkout starts · 7d',orders7.count||0],['Paid orders · 30d',paidCount],['Revenue · 30d',money(revenue)]].map(([k,v])=><div key={String(k)} className="panel p-5"><p className="text-[10px] font-black uppercase tracking-[.12em] text-[#8c7440]">{k}</p><p className="mt-2 text-3xl font-black text-[#23324a]">{v}</p></div>)}</div>
  <section className="mt-8 panel overflow-hidden"><div className="border-b p-6"><p className="eyebrow">Primary funnel split</p><h2 className="mt-2 text-2xl font-black text-[#23324a]">Company → Weddings → Family reunions</h2><p className="mt-2 text-sm text-[#687386]">Travel is attributed only within a real event context, not as a standalone segment.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-[#fbfaf7] text-[10px] uppercase tracking-[.11em] text-[#8b94a2]"><tr><th className="p-4">Segment</th><th className="p-4">Recent previews</th><th className="p-4">Recent orders</th><th className="p-4">Paid · 30d</th><th className="p-4">Revenue · 30d</th></tr></thead><tbody>{segmentStats.map(x=><tr key={x.seg} className="border-t"><td className="p-4 font-black text-[#23324a]">{label(x.seg)}</td><td className="p-4">{x.previews}</td><td className="p-4">{x.orders}</td><td className="p-4">{x.paid}</td><td className="p-4 font-black">{money(x.revenue)}</td></tr>)}</tbody></table></div></section>
  <div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="panel overflow-hidden"><div className="p-6"><p className="eyebrow">Orders</p><h2 className="mt-2 text-xl font-black text-[#23324a]">Latest checkout activity</h2></div><div className="divide-y">{(recentOrders.data||[]).map((o:any)=><div key={o.id} className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="font-black text-[#23324a]">{o.customer_email||'Email pending'}</p><p className="mt-1 text-xs text-[#7a8595]">{label(o.event_segment)} · {o.tier} · {new Date(o.created_at).toLocaleString()}</p></div><div className="text-right"><p className="font-black">{money(o.amount_cents)}</p><p className={`mt-1 text-[10px] font-black uppercase ${o.status==='paid'?'text-green-700':'text-[#9a7b31]'}`}>{o.status}</p></div></div>{(o.stripe_checkout_session_id||o.stripe_payment_intent_id)&&<p className="mt-2 break-all text-[10px] text-[#9aa2ad]">{o.stripe_checkout_session_id||o.stripe_payment_intent_id}</p>}</div>)}</div></section>
  <section className="panel overflow-hidden"><div className="p-6"><p className="eyebrow">Events</p><h2 className="mt-2 text-xl font-black text-[#23324a]">Latest generated plans</h2></div><div className="divide-y">{(recentDrafts.data||[]).map((d:any)=><div key={d.draft_token} className="p-5"><div className="flex items-start justify-between gap-4"><div><p className="font-black text-[#23324a]">{d.event_summary?.name||'Untitled event'}</p><p className="mt-1 text-xs text-[#7a8595]">{label(d.event_segment)} · {d.event_summary?.eventDate||'Date not set'} · {d.event_summary?.guestCount||0} guests</p></div><p className="text-[10px] font-black uppercase text-[#9a7b31]">{d.recommended_tier}</p></div></div>)}</div></section></div>
  <section className="mt-8 panel overflow-hidden"><div className="p-6"><p className="eyebrow">Activity stream</p><h2 className="mt-2 text-xl font-black text-[#23324a]">Latest conversion events</h2></div><div className="divide-y">{(activity.data||[]).map((a:any)=><div key={a.id} className="grid gap-2 p-4 text-sm sm:grid-cols-[180px_160px_1fr]"><span className="font-black text-[#23324a]">{a.event_name}</span><span className="text-[#8b7440]">{label(a.event_segment)}</span><span className="text-[#7a8595]">{new Date(a.created_at).toLocaleString()}</span></div>)}</div></section>
</section></main>
}
