import { ArrowRight, CalendarClock, Check, Layers3, ShieldCheck, UsersRound } from 'lucide-react'

const softwareSchema = {
  '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'RunYourEvent', applicationCategory: 'BusinessApplication', operatingSystem: 'Web',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://runyourevent.com',
  description: 'Event execution platform for turning event ideas into connected operating plans with workstreams, owners, dependencies, approvals, risks and deadlines.',
  offers: { '@type': 'AggregateOffer', lowPrice: '19', highPrice: '39', priceCurrency: 'USD', offerCount: '2' },
}
const faq = [
  ['What is RunYourEvent?', 'RunYourEvent turns an event idea, operating context and fixed date into an executable operating plan with workstreams, tasks, owners, dependencies, deadlines, approvals, risks and completion criteria.'],
  ['Is this event planning software?', 'RunYourEvent is positioned as an event execution platform. It focuses on defining and controlling the operational work required to deliver the event rather than inspiration, ticketing, registration or attendee engagement.'],
  ['Does it replace Asana, Monday or ClickUp?', 'No. RunYourEvent determines the event operating model first. Teams can then execute that model directly or move the work into their preferred project-management environment.'],
  ['What does it cost?', 'The preview is free. Essential is $19 per event and Professional is $39 per event. Teams and agencies can request custom access.'],
]
const faqSchema = { '@context':'https://schema.org','@type':'FAQPage',mainEntity:faq.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}})) }
const operatingModel = [
  ['Events','The complete project and fixed delivery outcome.'],['Workstreams','Venue, guests, catering, production, logistics and more.'],['Tasks','The individual actions required to move the event forward.'],['Deliverables','Defined outputs that make progress observable.'],['Owners','The people accountable for getting work done.'],['Dependencies','What has to happen before something else can begin.'],['Approvals','Decisions requiring confirmation before work can move.'],['Risks','Issues that could disrupt delivery.'],['Run of Show','The live-event sequence, handoffs and execution moments.'],['Completion Criteria','The evidence that defines done.'],
]
const audiences = [
  ['Private events','Know exactly what needs to happen next.','/weddings'],
  ['Corporate events','Give every workstream an owner and every deadline visibility.','/corporate'],
  ['Event teams & agencies','Standardize execution without forcing every event into the same template.','/agencies'],
  ['Hotels & venues','Coordinate clients, suppliers and internal teams from one operating plan.','/venues'],
]
export default function HomePage(){return <main>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(softwareSchema)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/>
<section className="bg-[#fbfaf7]"><div className="shell grid min-h-[690px] items-center gap-12 py-16 lg:grid-cols-[1.03fr_.97fr]"><div><p className="eyebrow">Event execution, organized</p><h1 className="display mt-5 text-5xl font-black leading-[.98] sm:text-7xl">Run your entire event <span className="block text-[#9d7c2f]">without losing track of anything.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#647084]">Turn your event into clear workstreams, tasks, owners, dependencies and deadlines—from first decision to final delivery.</p><p className="mt-4 max-w-2xl text-base font-black leading-7 text-[#23324a]">Every task. Every owner. Every deadline.</p><div className="mt-8 flex flex-wrap gap-3"><a href="/custom" className="btn-primary">Build my event plan <ArrowRight className="ml-2" size={16}/></a><a href="#how" className="btn-secondary">See how it works</a></div><div className="mt-7 flex flex-wrap gap-5 text-sm font-semibold text-[#788395]">{['Free preview','Complete plans from $19/event','No subscription for single events'].map(x=><span key={x} className="flex items-center gap-2"><Check size={15} className="text-[#a07f31]"/>{x}</span>)}</div></div>
<div className="panel overflow-hidden"><div className="bg-[#15233f] p-6 text-white"><p className="text-[10px] uppercase tracking-[.14em] text-white/45">350-person customer conference · 14 Aug</p><div className="mt-3 flex items-end justify-between gap-6"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#efcd6d]">One event becomes</p><h2 className="mt-1 text-xl font-black">A connected operating plan</h2></div><div className="text-right"><p className="text-xs text-white/45">Readiness</p><p className="text-3xl font-black text-[#efcd6d]">72%</p></div></div></div><div className="p-6"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[['Tasks','47'],['Workstreams','7'],['Dependencies','11'],['Approvals','4']].map(([l,v])=><div className="metric" key={l}><p className="text-[9px] uppercase text-[#9299a5]">{l}</p><p className="mt-1 text-lg font-black">{v}</p></div>)}</div><div className="mt-6 rounded-2xl border border-black/[.055] bg-[#fbfaf7] p-5"><p className="text-[10px] font-black uppercase tracking-[.12em] text-[#9a7b31]">Next critical chain</p><div className="mt-4 space-y-3">{['Venue confirmed','Floorplan approved','AV quantities locked','Vendor PO released','Technical rehearsal'].map((x,i)=><div className="flex items-center gap-3" key={x}><span className="grid h-7 w-7 place-items-center rounded-full bg-[#f3ead2] text-[10px] font-black text-[#80631f]">{i+1}</span><span className="font-bold text-[#23324a]">{x}</span></div>)}</div></div><div className="mt-4 rounded-2xl border border-[#eadfbd] bg-[#fbf7ea] p-4"><p className="text-sm font-black text-[#5f4b1f]">Floorplan approval is four days late.</p><p className="mt-1 text-xs leading-5 text-[#8b7440]">AV quantities, vendor ordering and rehearsal readiness are now exposed.</p></div></div></div></div></section>
<section id="how" className="border-y border-black/[.055] bg-[#f5f2ea] py-20"><div className="shell"><p className="eyebrow">The brand promise</p><h2 className="display mt-4 text-4xl font-black sm:text-5xl">Plan it. Assign it. Run it.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{[[CalendarClock,'Plan it.','Start from the event date and outcome. RunYourEvent builds the work backwards into a sequence that can actually be delivered.'],[UsersRound,'Assign it.','Give every workstream and task clear accountability instead of relying on memory, inboxes and scattered spreadsheets.'],[ShieldCheck,'Run it.','See blockers, approvals, risks and readiness before they become event-day surprises.']].map(([Icon,t,b]:any)=><article key={t} className="rounded-[28px] border border-black/[.055] bg-white p-7"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#15233f] text-[#efcd6d]"><Icon size={19}/></span><h3 className="mt-5 text-xl font-black text-[#23324a]">{t}</h3><p className="mt-3 text-sm leading-6 text-[#6f7a8b]">{b}</p></article>)}</div></div></section>
<section id="product" className="bg-white py-24"><div className="shell grid gap-12 lg:grid-cols-[.78fr_1.22fr]"><div><p className="eyebrow">Event Execution Platform</p><h2 className="display mt-4 text-4xl font-black sm:text-5xl">The event is the project. The operating model is the product.</h2><p className="mt-5 text-base leading-7 text-[#687386]">RunYourEvent turns an event idea into an executable plan—and keeps everyone accountable until the work is complete.</p></div><div className="grid gap-px overflow-hidden rounded-[28px] border border-black/[.055] bg-black/[.055] sm:grid-cols-2">{operatingModel.map(([t,b],i)=><div key={t} className="bg-[#fbfaf7] p-5"><div className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#f3ead2] text-[10px] font-black text-[#80631f]">{String(i+1).padStart(2,'0')}</span><h3 className="font-black text-[#23324a]">{t}</h3></div><p className="mt-3 text-sm leading-6 text-[#707b8c]">{b}</p></div>)}</div></div></section>
<section className="bg-[#15233f] py-24 text-white"><div className="shell grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#efcd6d]">Why execution software matters</p><h2 className="display mt-4 text-4xl font-black sm:text-5xl">When one thing slips, know what moves with it.</h2><p className="mt-5 max-w-xl text-base leading-7 text-white/60">A task list tells you what exists. An execution model tells you what is now blocked, what must move and who needs to act.</p></div><div className="rounded-[30px] border border-white/10 bg-white/[.04] p-6 sm:p-8"><div className="grid gap-4 sm:grid-cols-[1fr_auto_1fr_auto_1fr] sm:items-center">{[['Floorplan approval','4 days late'],['AV quantities','Blocked'],['Technical rehearsal','At risk']].map(([t,s],i)=><div className="contents" key={t}><div className="rounded-2xl border border-white/10 bg-white/[.05] p-4"><p className="text-xs font-black uppercase tracking-[.1em] text-white/45">{t}</p><p className={`mt-2 text-lg font-black ${i===0?'text-[#efcd6d]':'text-white'}`}>{s}</p></div>{i<2&&<ArrowRight className="hidden text-[#efcd6d] sm:block" size={18}/>}</div>)}</div></div></div></section>
<section id="use-cases" className="bg-[#f5f2ea] py-24"><div className="shell"><p className="eyebrow">Built for the people doing the work</p><div className="mt-4 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><h2 className="display max-w-4xl text-4xl font-black sm:text-5xl">One execution model. Different event realities.</h2><a className="btn-secondary" href="/event-types">Explore event types</a></div><div className="mt-10 grid gap-5 md:grid-cols-2">{audiences.map(([t,b,h])=><a key={t} href={h} className="group rounded-[28px] border border-black/[.055] bg-white p-7 transition hover:-translate-y-0.5 hover:border-[#c9aa57]"><p className="text-[10px] font-black uppercase tracking-[.13em] text-[#9a7b31]">{t}</p><h3 className="mt-3 text-2xl font-black text-[#23324a]">{b}</h3><span className="mt-6 inline-flex items-center text-sm font-black text-[#9a7b31]">See how it works <ArrowRight className="ml-2" size={14}/></span></a>)}</div></div></section>
<section className="bg-white py-24"><div className="shell grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="eyebrow">Reference models</p><h2 className="display mt-4 text-4xl font-black sm:text-5xl">Do not start from a blank page.</h2><p className="mt-5 text-base leading-7 text-[#687386]">Use structured event references as a starting point, then generate the right-sized operating plan for your own event, team, venue status and fixed date.</p><div className="mt-7 flex flex-wrap gap-3"><a href="/templates" className="btn-primary">Explore templates <ArrowRight className="ml-2" size={15}/></a><a href="/custom" className="btn-secondary">Build my event plan</a></div></div><div className="grid gap-4 sm:grid-cols-2">{[['Corporate conference','Program, venue, production, guests and approvals'],['Wedding','Venue, ceremony, guests, vendors, run of show'],['Executive retreat','Travel, accommodation, agenda, facilitation, logistics'],['Product launch','Production, content, approvals, press, guest operations']].map(([t,b])=><div key={t} className="rounded-[24px] border border-black/[.055] bg-[#fbfaf7] p-5"><Layers3 size={17} className="text-[#9a7b31]"/><h3 className="mt-4 font-black text-[#23324a]">{t}</h3><p className="mt-2 text-sm leading-6 text-[#707b8c]">{b}</p></div>)}</div></div></section>
<section className="border-y border-black/[.055] bg-[#f5f2ea] py-24"><div className="shell text-center"><p className="eyebrow justify-center">Simple event pricing</p><h2 className="display mx-auto mt-4 max-w-4xl text-4xl font-black sm:text-5xl">Preview free. Complete execution plans from $19.</h2><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-[#687386]">Essential is complete for straightforward events. Professional adds deeper approval, risk, contingency, vendor and critical-path intelligence.</p><div className="mt-8 flex justify-center gap-3"><a href="/custom" className="btn-primary">Build my event plan <ArrowRight className="ml-2" size={15}/></a><a href="/pricing" className="btn-secondary">See pricing</a></div></div></section>
<section className="bg-white py-24"><div className="shell"><p className="eyebrow">Questions</p><h2 className="display mt-4 max-w-3xl text-4xl font-black sm:text-5xl">What RunYourEvent is — and what it is not.</h2><div className="mt-9 grid gap-4 md:grid-cols-2">{faq.map(([q,a])=><details key={q} className="rounded-[24px] border border-black/[.055] bg-[#fbfaf7] p-5"><summary className="cursor-pointer font-black text-[#23324a]">{q}</summary><p className="mt-3 text-sm leading-6 text-[#707b8c]">{a}</p></details>)}</div></div></section>
<section className="bg-[#15233f] py-20 text-white"><div className="shell flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#efcd6d]">RunYourEvent</p><h2 className="display mt-3 text-4xl font-black">Every task. Every owner. Every deadline.</h2></div><a href="/custom" className="btn-signal shrink-0">Build my event plan <ArrowRight className="ml-2" size={15}/></a></div></section>
</main>}
