import { ArrowRight, Check, CircleAlert, GitBranch, Layers3, ShieldCheck } from 'lucide-react'

const faq=[
 ['What is DEngine?','DEngine is Event Execution Intelligence: it turns an event brief and fixed date into the operational model of what must become true before the event is ready.'],
 ['Is this another project-management tool?','No. DEngine constructs the event operating model first. Your team can still execute that model in Asana, Monday, ClickUp or another PM system.'],
 ['Is it just an AI checklist?','No. The output is structured around workstreams, dependencies, backward timing, owners, approvals, completion criteria, risk and contingency.'],
 ['What does it cost?','The preview is free. Essential is $19 per event and Professional is $39 per event. Teams and agencies can request custom access.']
]
const softwareSchema={ '@context':'https://schema.org','@type':'SoftwareApplication',name:'DEngine',applicationCategory:'BusinessApplication',operatingSystem:'Web',url:process.env.NEXT_PUBLIC_SITE_URL||'https://dengine.vercel.app',description:'Event Execution Intelligence software that builds dependency-aware plans backwards from a fixed event date.',offers:{'@type':'AggregateOffer',lowPrice:'19',highPrice:'39',priceCurrency:'USD',offerCount:'2'} }

export default function HomePage(){return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(softwareSchema)}}/><section className="bg-[#fbfaf7]"><div className="shell grid min-h-[680px] items-center gap-12 py-16 lg:grid-cols-[1.02fr_.98fr]"><div><p className="eyebrow">Event Execution Intelligence</p><h1 className="display mt-5 text-5xl font-black leading-[.98] sm:text-7xl">Your event date is fixed.<span className="mt-2 block text-[#9d7c2f]">Build everything backwards.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#647084]">DEngine turns one event brief into the operational plan: workstreams, dependencies, owners, deadlines, approvals, risks and the evidence required to call each item done.</p><div className="mt-8 flex flex-wrap gap-3"><a href="/custom" className="btn-primary">Build my execution plan <ArrowRight className="ml-2" size={16}/></a><a href="/browse" className="btn-secondary">Explore reference models</a></div><div className="mt-7 flex flex-wrap gap-5 text-sm font-semibold text-[#788395]">{['Free preview','Complete plans from $19/event','No subscription for single events'].map(x=><span key={x} className="flex items-center gap-2"><Check size={15} className="text-[#a07f31]"/>{x}</span>)}</div></div><div className="panel overflow-hidden"><div className="bg-[#15233f] p-6 text-white"><p className="text-[10px] uppercase tracking-[.14em] text-white/45">Customer Conference · Berlin</p><div className="mt-2 flex items-end justify-between"><h2 className="text-xl font-black">Event execution model</h2><div><p className="text-xs text-white/45">Readiness</p><p className="text-3xl font-black text-[#efcd6d]">72%</p></div></div></div><div className="p-6"><div className="grid grid-cols-3 gap-3">{[['Critical path','2 at risk'],['Approvals','6 open'],['Next hard date','14 Aug']].map(([a,b])=><div key={a} className="metric"><p className="text-[9px] uppercase text-[#9299a5]">{a}</p><p className="mt-1 font-black">{b}</p></div>)}</div><div className="mt-6 space-y-3">{['Venue confirmed','Floorplan locked','AV scope issued','Show file approved','Technical rehearsal'].map((x,i)=><div key={x} className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#f3ead2] text-[10px] font-black text-[#80631f]">T{String((i+1)*6).padStart(2,'0')}</span><span className="font-bold text-[#23324a]">{x}</span></div>)}</div><div className="mt-6 rounded-2xl border border-[#eadfbd] bg-[#fbf7ea] p-4"><div className="flex gap-3"><CircleAlert className="text-[#9d7c2f]" size={17}/><div><p className="text-sm font-black text-[#5f4b1f]">Floorplan approval is four days late.</p><p className="mt-1 text-xs text-[#8b7440]">AV design, quantities and load-in remain blocked.</p></div></div></div></div></div></div></section>
<section className="bg-[#f5f2ea] py-24"><div className="shell"><p className="eyebrow">The product distinction</p><h2 className="display mt-4 max-w-4xl text-4xl font-black sm:text-5xl">Tasks are not the hard part. <span className="text-[#7c8797]">Knowing what depends on what is.</span></h2><div className="mt-10 grid gap-5 lg:grid-cols-3">{[['Generic AI','Produces plausible lists, but leaves sequencing, completeness and prerequisites to the planner.'],['Project-management software','Tracks work once the team already knows the work, owners and dates.'],['DEngine','Constructs the event operating model: dependencies, approvals, completion rules, risks and backward timing.']].map(([a,b],i)=><article key={a} className={`rounded-[28px] border p-7 ${i===2?'border-[#c9aa57] bg-[#15233f] text-white':'border-black/[.055] bg-white'}`}><h3 className="text-xl font-black">{a}</h3><p className={`mt-3 text-sm leading-6 ${i===2?'text-white/60':'text-[#687386]'}`}>{b}</p></article>)}</div></div></section>
<section className="bg-white py-24"><div className="shell"><p className="eyebrow">The Event Execution Graph</p><h2 className="display mt-4 max-w-3xl text-4xl font-black sm:text-5xl">One operational model. Every prerequisite connected.</h2><div className="mt-10 grid gap-4 md:grid-cols-3">{[[GitBranch,'Dependencies','What must happen first and what becomes blocked when it slips.'],[Layers3,'Workstreams','Venue, production, content, guests, suppliers and other domains stay structurally separated.'],[ShieldCheck,'Definition of done','Completion criteria and evidence make finished observable rather than subjective.']].map(([Icon,a,b]:any)=><article key={a} className="rounded-[26px] border border-black/[.055] bg-[#fbfaf7] p-6"><Icon className="text-[#9a7b31]"/><h3 className="mt-5 text-lg font-black text-[#23324a]">{a}</h3><p className="mt-2 text-sm leading-6 text-[#707b8c]">{b}</p></article>)}</div></div></section>
<section className="bg-[#15233f] py-20 text-white"><div className="shell grid gap-5 md:grid-cols-3">{[['Preview','$0','Prove DEngine understands the event before you buy.'],['Essential','$19/event','Complete right-sized execution plan for a straightforward event.'],['Professional','$39/event','Deeper approvals, risk, contingency, vendor and critical-path intelligence.']].map(([a,b,c])=><article key={a} className="rounded-[26px] border border-white/10 p-6"><p className="text-xs font-black uppercase tracking-[.13em] text-[#efcd6d]">{a}</p><p className="mt-3 text-3xl font-black">{b}</p><p className="mt-3 text-sm leading-6 text-white/55">{c}</p></article>)}</div><div className="shell mt-8"><a className="btn-signal" href="/pricing">See pricing <ArrowRight className="ml-2" size={15}/></a></div></section>
<section className="bg-[#fbfaf7] py-24"><div className="shell max-w-4xl"><p className="eyebrow">FAQ</p><div className="mt-8 divide-y divide-black/[.06] border-y border-black/[.06]">{faq.map(([q,a])=><div key={q} className="py-6"><h3 className="font-black text-[#23324a]">{q}</h3><p className="mt-2 text-sm leading-6 text-[#687386]">{a}</p></div>)}</div></div></section></main>}
