-- DEngine commerce layer.
-- The production project already has this schema; this migration keeps repository history reproducible.
create extension if not exists pgcrypto;

create table if not exists public.dengine_plan_drafts (
  id uuid primary key default gen_random_uuid(),
  draft_token uuid not null unique,
  plan_ciphertext text not null,
  plan_iv text not null,
  plan_tag text not null,
  preview jsonb not null default '{}'::jsonb,
  event_summary jsonb not null default '{}'::jsonb,
  recommended_tier text not null check (recommended_tier in ('essential','professional')),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists idx_dengine_plan_drafts_token on public.dengine_plan_drafts(draft_token);
create index if not exists idx_dengine_plan_drafts_expiry on public.dengine_plan_drafts(expires_at);

create table if not exists public.dengine_orders (
  id uuid primary key default gen_random_uuid(),
  draft_token uuid not null,
  tier text not null check (tier in ('essential','professional')),
  amount_cents integer not null check (amount_cents in (1900,3900)),
  currency text not null default 'usd' check (currency = 'usd'),
  stripe_checkout_session_id text unique,
  stripe_payment_intent_id text,
  customer_email text,
  status text not null default 'checkout_created' check (status in ('checkout_created','paid','expired','refunded')),
  accepted_terms_at timestamptz,
  immediate_performance_consent_at timestamptz,
  created_at timestamptz not null default now(),
  verified_at timestamptz
);

create index if not exists idx_dengine_orders_draft on public.dengine_orders(draft_token);
create index if not exists idx_dengine_orders_session on public.dengine_orders(stripe_checkout_session_id);

create table if not exists public.dengine_conversion_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('preview_started','preview_generated','tier_recommended','pricing_viewed','checkout_started','purchase_completed')),
  draft_token uuid,
  anonymous_session text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_dengine_conversion_event_name on public.dengine_conversion_events(event_name);
create index if not exists idx_dengine_conversion_created_at on public.dengine_conversion_events(created_at desc);

alter table public.dengine_plan_drafts enable row level security;
alter table public.dengine_orders enable row level security;
alter table public.dengine_conversion_events enable row level security;

revoke all on table public.dengine_plan_drafts from anon, authenticated;
revoke all on table public.dengine_orders from anon, authenticated;
revoke all on table public.dengine_conversion_events from anon, authenticated;
