import type { Metadata } from 'next'
import { ArrowRight, Check } from 'lucide-react'

export const metadata: Metadata = { title:'DEngine Pricing — $19 Essential / $39 Professional', description:'Preview free. Unlock a complete single-event execution plan from $19 with no subscription required.', alternates:{ canonical:'/pricing' } }

const plans = [
 {name:'Preview',price:'$0',eyebrow:'Prove the model',copy:'See whether DEngine understands the shape and complexity of your event before paying.',features:['Event architecture summary','Workstream count','Representative dependency-aware tasks','Complexity assessment','Tier recommendation'],cta:'Build free preview',href:'/custom'},
 {name:'Essential',price:'$19',suffix:'/ event',eyebrow:'Straightforward events',copy:'A complete, right-sized execution plan for a genuinely simpler event — never deliberately truncated.',features:['Complete task coverage','Owners and backward timing','Dependencies','Completion criteria','Event-date anchored schedule','No subscription'],cta:'Start with a preview',href:'/custom'},
 {name:'Professional',price:'$39',suffix:'/ event',eyebrow:'Complex professional events',copy:'Adds the deeper control layer needed when approvals, risks, suppliers and critical paths matter.',features:['Everything in Essential','Approval gates + approvers','Risk consequences','Contingencies','Critical-path detail','Vendor/procurement scope'],cta:'Start with a preview',href:'/custom',featured:true},
 {name:'Teams & Agencies',price:'Custom',eyebrow:'Repeat event operations',copy:'For organizations that want reusable event models, portfolio readiness and integrations.',features:['Concurrent events','Reusable organization models','Company approval rules','Portfolio readiness','Historical event intelligence','PM/calendar integrations'],cta:'Discuss team access',href:'mailto:hello@dengine.app?subject=DEngine%20team%20access'}
]

export default function PricingPage(){ return <main className="bg-[#fbfaf7]"><section className="shell pb-14 pt-20 text-center"><p className="eyebrow">Pricing</p><h1 className="display mx-auto mt-4 max-w-4xl text-5xl font-black sm:text-6xl">Preview free. <span className="text-[#8b7440]">Complete plans from $19.</span></h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-[#6f7a8b]">Price follows execution complexity — not the label attached to the event. No subscription is required for a single event.</p></section><section className="shell pb-24"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{plans.map((p:any)=><article key={p.name} className={`rounded-[30px] border p-7 ${p.featured?'border-[#c9aa57] bg-[#15233f] text-white':'border-black/[.06] bg-white'}`}><p className={`text-[10px] font-black uppercase tracking-[.13em] ${p.featured?'text-[#efcd6d]':'text-[#9b7b2f]'}`}>{p.eyebrow}</p><h2 className="mt-3 text-xl font-black">{p.name}</h2><p className="mt-5 text-4xl font-black">{p.price} {p.suffix&&<span className="text-sm opacity-50">{p.suffix}</span>}</p><p className={`mt-4 min-h-[96px] text-sm leading-6 ${p.featured?'text-white/60':'text-[#707b8c]'}`}>{p.copy}</p><ul className="mt-6 space-y-3">{p.features.map((f:string)=><li key={f} className="flex gap-2 text-sm"><Check size={15} className="mt-0.5 shrink-0 text-[#d8b65b]"/><span>{f}</span></li>)}</ul><a className={`${p.featured?'btn-signal':'btn-primary'} mt-7 w-full`} href={p.href}>{p.cta}<ArrowRight className="ml-2" size={15}/></a></article>)}</div><div className="mt-10 rounded-[26px] border border-[#ded2aa] bg-[#fbf6e7] p-6"><p className="font-black text-[#5f4b1f]">DEngine does not deliberately hide necessary tasks to force an upgrade.</p><p className="mt-2 text-sm leading-6 text-[#8b7440]">Essential is complete for a simpler event. Professional costs more because it exposes deeper execution intelligence around approvals, risk, contingency, vendor scope and critical path.</p></div></section></main> }
